version: "3.9"
services:
  web:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/app
    command: /start-reload.sh
    environment:
      - DATABASE_URL=postgresql://usos_user:usos_password@db/usos_db
    depends_on:
      - "db"
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    # expose:
    #  - 5432
    environment:
      - POSTGRES_USER=usos_user
      - POSTGRES_PASSWORD=usos_password
      - POSTGRES_DB=usos_db

volumes:
  postgres_data: